### PR TITLE
Update finepack to version 2.5.0 and add yarn.lock

### PR DESCRIPTION
**Pull request by matteocng**
- chore(package): update finepack to version 2.5.0
- chore: add yarn.lock
- docs: minor text rearrangements

### CODE REVIEW

**Comment by Kikobeats** [comment]
@matteocng  one question about `yarn.lock`. If I update npm dependencies, I suppose that I need to update `yarn.lock` as well.

how to?

**Comment by matteocng** [comment]
@Kikobeats if you [switch to `yarn`](https://yarnpkg.com/lang/en/docs/migrating-from-npm/) to manage `package.json` and the modules, it will automagically keep `yarn.lock` in sync, it is a built-in behaviour.

`npm install --save [package]` -> `yarn add [package]`
`npm install --save-dev [package]` -> `yarn add [package] [--dev/-D]`
`rm -rf node_modules && npm install` -> `yarn upgrade`
...

Also, a note about Travis:

> If your Node.js project has the yarn.lock file in the repository root, we proceed to install Yarn and execute the yarn command instead of the default npm install.
https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

**Comment by Kikobeats** [comment]
about that

> npm install --save-dev [package] -> yarn add [package] [--dev/-D]

I think that doesn't resolve all the scenario. What happens when I update a dependency range out of the dependency range lock, for example `~1.0.0` → `~2.0.0`. need I to force regenerate the lock file?

My opinion of yarn is that is good for production scenario but I feel a little afraid of being popular for all my projects, because need an additional maintenance layer.

I would have the same problem with `shrinkwrap`. In this case, is necessary do something like:

```
npm outdated+npm update+npm shrinkwrap
```

but is not intended for development environments.

Also, what's the point for create a yarn.lock in all the little modules, when you can just create a yarn.lock in your main big project? in this case, bumped main repository.

**Comment by matteocng** [comment]
Valid point, I don't know about `shrinkwrap`, but trying that test case, `yarn` seems to modify the lockfile automatically:

#### First step:

```bash
yarn add finepack@~1.0.0
```

`package.json`
```json
  "dependencies": {
    "finepack": "~1.0.0"
  }
```

`yarn.lock`
```
finepack@~1.0.0:
  resolved "https://registry.yarnpkg.com/finepack/-/finepack-1.0.2.tgz#447d51f8ea56b0f05cdcf0306cd181961d1c42f0"
```

#### Second step case #A:

```bash
yarn add finepack@~2.0.0
```
```json
  "dependencies": {
    "finepack": "~2.0.0"
  }
```

```
finepack@~2.0.0:
  resolved "https://registry.yarnpkg.com/finepack/-/finepack-2.0.2.tgz#acedd08de2681f0b71193ed05cc6a16cbc40a908"
```

#### Second step case #B or third step of case #A:

```bash
yarn upgrade finepack
```

```json
  "dependencies": {
    "finepack": "^2.5.0"
  }
```

```
finepack@^2.5.0:
  resolved "https://registry.yarnpkg.com/finepack/-/finepack-2.5.0.tgz#e3ef4eb253c8c86c38699a48e7a4b3df11692ef8"
```

Anyway, whether to use `yarn.lock` in libraries and not just production applications is an interesting topic. There is a nice write-up on [yarnpkg blog](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) that recommends using `yarn.lock` in both cases. I agree with that, even for smaller modules (more reliable installations, even if you have few dependencies), but It is also true that yarn is a relatively recent software and there may be edge cases about regenerating the lock, so as you said one could leave `yarn.lock` inside `bumped` but not the smaller modules. 😃

**Comment by Kikobeats** [comment]
One more thing here, the idea under `bumped-*` is that they are installed on demand, not explicitly by the user:

https://bumped.github.io/plugins.html

so no have sense has a `yarn.lock` because you shouldn't perform a `npm install` of this package.

What do you think about using yarn at `bumped` main repository at first step?

**Comment by Kikobeats** [comment]
If you want to know more about how bumped handle this:

https://github.com/bumped/bumped/blob/master/lib/Bumped.plugin.coffee#L40

In this line I can't use yarn because is not released with the node binary :'(

**Comment by matteocng** [comment]
@Kikobeats I think it is a good idea, I have closed all the `yarn.lock` PRs excluidng the one for [bumped ](/bumped/bumped/pull/80).

**Comment by Kikobeats** [comment]
👍

**Pull request merged**
